# Generated by Django 4.2.2 on 2023-07-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveproduct',
            name='comment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
