# Generated by Django 4.2.2 on 2023-06-27 13:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='saveproduct',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='saveproduct',
            name='detailed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
