# Generated by Django 4.2.2 on 2023-07-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRestaurant',
        ),
    ]
