# Generated by Django 4.2.2 on 2023-07-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_saveproduct_managers_and_more'),
        ('payment', '0002_orderrestaurant_delete_restaurantpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrestaurant',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.restaurant'),
        ),
        migrations.AlterField(
            model_name='orderrestaurant',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
