# Generated by Django 4.2.2 on 2023-07-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderrestaurant_expire_orderrestaurant_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrestaurant',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='orderrestaurant',
            name='number',
        ),
        migrations.AddField(
            model_name='orderrestaurant',
            name='phone',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
